metric_file_path = 'src/resources/metric.parquet'
loss_file_path = 'src/resources/loss.parquet'
parquet_engine = 'fastparquet'
credit_data_path = 'src/resources/creditcard_data.parquet'
ecg_data_path = 'src/resources/ecg_data.parquet'